name: C&J Auto
short_name: Car Repair
theme_name: default
plugins:
  - jekyll-seo-tag
remote_theme: yggilabs/boilerplate
logo: /assets/images/icon.png
social:
  name: C&J Auto
  links:
    - https://www.facebook.com/CJ-Auto-114123749942783/
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
    values:
      image: /assets/images/C&JAuto-StackRev72.png
