name: Osseo Auto Service
short_name: Car Repair
theme_name: default
plugins:
  - jekyll-seo-tag
remote_theme: yggilabs/boilerplate
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default-card.png
